### ISSUE TITLE
Tambah Nomor Workshop

### ISSUE THREAD

**Issue by ajiyakin** [majalengkadev/blog-php#1]
Kang @IhwanID , mungkin bakalan lebih gampang buat temen-temen yang nanti nyari materinya kalo ditambahin nomor workshop yang ke berapa. Jadi nanti tinggal ditambahin di READMEnya. Ini workshop pertama kan yah? Apa udah ke berapa kali? Biar saya bantu tambahin di READMEnya.

**Comment by IhwanID** [comment]
Gini kang @ajiyakin , sebenarnya repo ini sama isinya dengan yang repo  https://github.com/majalengkadev/workshop-blog  hehe. Salah saya sih waktu bikin repo workshop blog lupa dibikinin branch per hari nya. jadi workshopnya 4 hari. nah hari pertama kan fundamental, jadi belum create project. hari kedua templating, hari ke tiga bikin CRUD, hari ke 4 deploy ke hosting. masalah baru muncul pas hari ke 3 dimana pesertanya ada yang ga hadir di hari ke dua. jadi dilema, masa mau ngulangin materi yang sama hehe, jadi saya upload ke sini. kayaknya saya harus belajar make git yang benar ke kang aji hehe.

**Comment by ajiyakin** [comment]
Ah I see. OK kalo gitu. Saran sayamah sih buat next workshop dijadiin satu repo, terus dikasih nomor di nama reponya. Jangan lupa README oge kang :smile:
